### ISSUE TITLE
It's no longer possible to change the PWA icons?

### ISSUE THREAD

**Issue by kazukyakayashi** [NeoApplications/Neo-Launcher#372] opened 2023-07-25 11:02 UTC
## Description
I've just updated my old version 8.1 (*Omega Launcher*), but unfortunately my backup crashed Neo Launcher. 

So I'm redoing everything by hand but it's now impossible to change the PWA icons (*install via Firefox/Fennec or even Bromite*). Has this option disappeared or is it just a bug?

## Device and OS

* Device: OnePlus 6T
* Android version: 11
* Launcher version: 1.6.1 (IzzyOnDroid)

**Comment by saulhdev** [comment] 2023-08-05 01:39
Duplicate of #208

**Closed by saulhdev** 2023-08-05 01:39 UTC
