### ISSUE TITLE
[Feature Request] Change UI font

### ISSUE THREAD

**Issue by bkazoo** [NeoApplications/Neo-Launcher#350] opened 2023-05-23 16:50 UTC
It would be great if there was a possibility to change the UI font, I would love to see Inter available (https://rsms.me/inter/) but I'm sure others will have other preferences :-)

Maybe a chooser that allows to select a font file available in the available files for the user could satisfy this need for everyone?

**Comment by alexanderadam** [comment] 2023-05-27 08:46
duplicate of #187

**Closed** 2023-05-27 23:05 UTC
