### ISSUE TITLE
[Feature request] Infinite scrolling

### ISSUE THREAD

**Issue by Knud3** [NeoApplications/Neo-Launcher#164] opened 2022-05-02 10:01 UTC
Launcher have every possible features what comes to mind, but it is missing infinite scrolling.

As if user have multiple desktops then after swiping to left on last desktop it gets back to first desktop (and vise versa).

**Comment by basings** [comment] 2022-06-27 08:10
duplicate of  #101 ?

**Closed** 2022-06-27 08:34 UTC
