### ISSUE TITLE
[Feature Request] Reset custom icons shortcut

### ISSUE THREAD

**Issue by Joeb3** [NeoApplications/Neo-Launcher#377] opened 2023-07-29 12:42 UTC
It would be nice to have a function to restore custom icons, such as there is on Nova Launcher

![BQvUE](https://github.com/NeoApplications/Neo-Launcher/assets/92218664/b1ca1888-5d3a-413b-8198-43c3f8230c97)

I've looked through all the menus, but haven't found anything like this in the current release.
For those who often change the icons it is a very useful function.

**Comment by saulhdev** [comment] 2023-08-01 03:52
duplicate of #359

**Closed by saulhdev** 2023-08-01 03:52 UTC
