### ISSUE TITLE
Multi-account device: desktop grid height resets when switching account

### ISSUE THREAD

**Issue by 16NoCo** [NeoApplications/Neo-Launcher#135] opened 2021-11-09 10:25 UTC
## Description
I have a device with 2 user accounts: a main one for me, and another for someone else who doesn't have a smartphone and who sometimes needs to use my phone.
First only my (main) user account had Omega installed, and every time I switch to the other account and back to mine, the height of the 'desktop' grid resets back to 5.

Trying to work-around that issue, I installed Omega on the other account. But that does not help, and the launcher in the other account seems to be completely reset (at least all apps manually placed on the desktop disappear) sometimes when I switch accounts.

## Expected Behavior
When switching android accounts, the launcher of each account should not be affected.

## Actual Behavior
When switching android accounts, at least the 'desktop' grid height resets back to 5 on the main account.

## Steps to Reproduce
1. Add another user account to the device
2. Change Omega's desktop grid height to 6 or 7
3. Switch to the other account
4. Switch back to the main account: the desktop grid height has been reset to 5
5. Reboot the device: the grid height is back to user's custom value (6 or 7 here). Most of the time, the icons that were on the 6+ rows are lost.

## Device and OS

* Device: Fairphone 3
* Android version: 10
* Launcher version: 0.8.1
* Rom: /e/OS 0.18-q-20210827132307

**Comment by mkmaslov** [comment] 2022-04-14 22:38
I have a similar and most likely related issue. Sometimes the desktop or the drawer randomly reset to standard 5-column layouts. I didn't yet figure out what it is related to, it may be the device reset. I am only using a single user account. My OS is GrapheneOS 2022041100 and I am using Omega Launcher 0.8.1. The issue is present on both Pixel 6 and Pixel 3a.

**Comment by saulhdev** [comment] 2022-07-12 23:47
Fixed on v0.9

**Closed by saulhdev** 2022-07-12 23:47 UTC
