### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ViktorKahu** [NeoApplications/Neo-Launcher#346] opened 2023-05-02 12:55 UTC
## Description

Please excuse me if its an inappropriate question, but when can we expect a new release?

I see that a lot of work has been done since the latest release, and unfortunately not all of us know how to build/reflect changes from github...

One issue that bugs me in particular is the homescreen continually resetting to default if not locked due to something to do with widget sizes. I see it's been resolved in january, but still no update...

Huge thanks to developers for an otherwise great launcher.

## Steps to Reproduce

1.
2.
3.
4.

## Device and OS

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by machiav3lli** [comment] 2023-05-02 21:13
As generally there's no ETA. We're rebasing the launcher on AOSP 13 and rewriting much of our previous additions, this will take much time and the project is currently in non-releasable state.

You can always install the apks generated with github actions, to test project's current state, but be aware that these apks aren't supported (no reports of issues will be considered or accepted).

**Comment by stephen-hill** [comment] 2023-05-09 13:27
@machiav3lli If a proper new version is a long way off, could you backport/merge critical fixes into a 0.9.4 release?

**Comment by machiav3lli** [comment] 2023-05-09 22:23
Can you please define what "critical fixes" would be. As most users use it with no real major issues, while only couple have reported having issue similar to #337 but still no clear source has been identified, but we hope that the current rewriting of many of the classes & patches would help avoid such.

Otherwise, the answer would be: Not really, most changes to the code are built over the A13 base and mostly aren't backportable.

**Comment by stephen-hill** [comment] 2023-05-10 10:03
@machiav3lli Yes, I would consider #337 and any other bugs that result in data loss critical.

Yesterday I upgraded from a much older version to 0.9.3. I would say that my home screen has been wiped clean or reset to default at least a dozen times.

I've now got into the habit of creating a backup before changing anything.

For instance, I just enabled the dock background color to see what it looked like, and it removed all of my home icons.

Cheers

**Comment by ViktorKahu** [comment] 2023-05-10 11:50
I would like to thank the developers for the work that they do, and give credit where it's due for a great launcher.

But the harsh reality is such, that by the time you guys adapt it for Android 13, Android 14 will be out and we will once again wait for a year for the new incompatibilities to be fixed, and then again, and so on.

I understand the limitations the developers face and that there is really no other way... but I see no point in any of this. The only people that can benefit from such a loop are those with older devices that no longer get updates.

On that note, I think that I will have to live with a stock launcher. Less features, but at least it works.

**Comment by stephen-hill** [comment] 2023-05-10 11:52
> I would like to thank the developers for the work that they do, and give credit where it's due for a great launcher.

Agreed, it is a great launcher.

**Comment by machiav3lli** [comment] 2023-05-10 12:02
@ViktorKahu Actually the aim of the rebasing and rewriting we're doing currently is to resolve much of the dependencies on the AOSP code base allowing for easier rebasing on newer versions, that's why it's taking much more time compared to our rebase on A12 last year (added to having less time to invest currently).

@stephen-hill As mentioned, the mentioned issue is still unclear as we were not able to reproduce it (and non of users provided any useful crashlogs), but we hope that rewriting the dbs would solve it, we'll possibly see with the first 1.0.0-alpha.

**Comment by stephen-hill** [comment] 2023-05-18 06:42
@machiav3lli How do I get the debug logs?

Since upgrading to the latest version, all settings reset completely atleast every 3 days.

There is no apparent crash, it just resets and I have to load a backup.

Quite often I will notice it after unlocking my phone.

**Comment by stephen-hill** [comment] 2023-05-18 09:02
@machiav3lli I'm trying to review the code interacts with the database and I noticed `LoaderTask.loadWorkspace.`

It appears at a cursory glance that should anything fail in `ImportDataTask.performImportIfPossible`, `GridSizeMigrationTaskV2.migrateGridIfNeeded`, or `GridSizeMigrationTask.migrateGridIfNeeded`, then the default action is to create an empty database. Is this correct?

If this is correct, then could we have a debug build that add as much logging as possible inside these call stacks?

It does, to me, appear as if it's possible for clearDb to get set to true, if something completely unrelated to the database fails, deep in side those methods.

**Comment by ViktorKahu** [comment] 2023-07-09 00:30
Just for a rough idea, in the current state of affairs, approximately how far along are we at rebasing the code (eg: 50%)?

**Comment by machiav3lli** [comment] 2023-07-09 07:43
We're almost done (itcs been mostly a 100% rebase, as AOSP have finally started to take working on the launcher seriously and we wanting to decouple things to ease future rebasing), maybe a week till a first alpha for the community

**Comment by ViktorKahu** [comment] 2023-07-09 08:18
Nice work!

With the new code base, will there be support for material you (eg: monochrome icons, etc...)?

**Comment by Fmstrat** [comment] 2023-08-06 17:19
@machiav3lli I've just submitted and subscribed to a few things in Issues that I was planning to contribute to, however this thread gives me pause. With the refactor, is this something I should take on now, or wait on?

**Comment by machiav3lli** [comment] 2023-08-07 05:35
@Fmstrat hey, we're actually nearing a first alpha release, starting from that point many issues would be inherently solved and mostly all kind of contribution is welcome, if you wish to already start on, you can gladly write me or @saulhdev on Telegram or Matrix

**Comment by Fmstrat** [comment] 2023-08-07 11:23
@machiav3lli sounds great, I'll probably hold until the alpha is ready to make things easier and get a better grasp of the state of things, first. Thanks!

**Comment by ViktorKahu** [comment] 2023-09-09 17:02
> We're almost done (itcs been mostly a 100% rebase, as AOSP have finally started to take working on the launcher seriously and we wanting to decouple things to ease future rebasing), maybe a week till a first alpha for the community

Here we are, 9 weeks later...

**Comment by Fmstrat** [comment] 2023-09-09 18:18
> Here we are, 9 weeks later...

I mean, feel free to contribute to speed things up on this software that is provided free of charge..

**Comment by Lightsockie** [comment] 2023-10-16 20:36
Almost a year since the last release lol. Thinkin the project must be abandonware tbh, which is too bad. I really liked what was being offered. Been waiting for a new build since the start of the year to hopefully fix some of the bugs and hangs, but prolly about time to accept my losses and use a different free-of-charge launcher. Things are getting progressively even more unstable

**Comment by Turhvjbufv** [comment] 2023-10-16 20:47
Project is still alive, new alpha soon @Lightsockie

**Comment by Lightsockie** [comment] 2023-10-18 18:06
@Turhvjbufv I mean even just a few months ago ITT the chatter was about rebasing to AOSP13. Meanwhile I'm currently on 14 lol. Its been "alpha soon" for like four months now, too. I do hope it actually comes soon, cuz the market for OSS launchers is pretty thin. I've started using stock now, which is pretty awful, but at least apps launch consistently

**Comment by eleius** [comment] 2023-12-06 06:39
0.9.3 released!

**Comment by Turhvjbufv** [comment] 2023-12-06 06:49
@eleius it's an old release that they accidently deleted and they released it again, it's not new

**Comment by machiav3lli** [comment] 2023-12-07 15:48
Here's two show-stoppers of the first alpha:
- Private life
- Facing some bugs using the A12/A13 bases on A14, we started migrating the base to A14, which is going smoothly locally for now.

**Comment by DeadSecTr** [comment] 2023-12-20 02:11
RE RE Release? Again? Whats that for? Again 0.9.3? What the....

**Comment by Turhvjbufv** [comment] 2023-12-20 06:34
Lol yeah

**Comment by Turhvjbufv** [comment] 2023-12-20 10:21
@ViktorKahu still no new release, why closed as completed?

**Comment by ViktorKahu** [comment] 2023-12-20 10:26
> @ViktorKahu still no new release, why closed as completed?

Because I no longer expect one.

This project had a lot of potential and I really wished that it would succeed, however, I think enough time has passed  to accept the inevitable and move on.

**Comment by Turhvjbufv** [comment] 2023-12-20 10:27
> > @ViktorKahu still no new release, why closed as completed?
> 
> Because I no longer expect one.
> 
> This project had a lot of potential and I really wished that it would succeed, however, I think enough time has passed  to accept the inevitable and move on.

I don't agree, but sure, at least close as not planned

**Comment by ViktorKahu** [comment] 2023-12-20 10:32
> > > @ViktorKahu still no new release, why closed as completed?
> > 
> > 
> > Because I no longer expect one.
> > This project had a lot of potential and I really wished that it would succeed, however, I think enough time has passed  to accept the inevitable and move on.
> 
> I don't agree, but sure, at least close as not planned

I am not a developer of this project and I have no control of how things are closed. All I can do is specify that I closed the issue that I raised, the rest is automatic.

**Comment by Turhvjbufv** [comment] 2023-12-20 10:33
> > > > @ViktorKahu still no new release, why closed as completed?
> > > 
> > > 
> > > Because I no longer expect one.
> > > This project had a lot of potential and I really wished that it would succeed, however, I think enough time has passed  to accept the inevitable and move on.
> > 
> > I don't agree, but sure, at least close as not planned
> 
> I am not a developer of this project and I have no control of how things are closed. All I can do is specify that I closed the issue that I raised, the rest is automatic.

You can reopen the issue, and then close it again and when you do that you have an option to close as not planned

**Comment by ViktorKahu** [comment] 2023-12-20 10:34
> > > > > @ViktorKahu still no new release, why closed as completed?
> > > > 
> > > > 
> > > > Because I no longer expect one.
> > > > This project had a lot of potential and I really wished that it would succeed, however, I think enough time has passed  to accept the inevitable and move on.
> > > 
> > > 
> > > I don't agree, but sure, at least close as not planned
> > 
> > 
> > I am not a developer of this project and I have no control of how things are closed. All I can do is specify that I closed the issue that I raised, the rest is automatic.
> 
> You can reopen the issue, and then close it again and when you do that you have an option to close as not planned

Done.

**Closed** 2023-12-20 10:34 UTC

**Comment by Turhvjbufv** [comment] 2023-12-20 10:36
What launcher are you going to use instead?

**Comment by ViktorKahu** [comment] 2023-12-20 10:44
I have no choice but to use the stock launcher as even the dev versions of this project don't work when shelter and a work profile are involved.

On A14, neo launcher simply crashes after you exit the app and try to reenter or restart the phone.

Also, the stock launcher has an option to freeze all apps in the launcher  work profile menu, no third party launcher that I am aware of does.

Other launchers I've tried, are either completely crap or have trackers and other filth. So yeah, stock GrapheneOS launcher. Not as cool as Neo (if it worked), but not the worst option out there.

**Comment by DeadSecTr** [comment] 2023-12-20 18:32
I am using now OLauncher right now....pretty good imho... :)

**Comment by John-Gee** [comment] 2024-03-26 14:44
Probably a stupid thought, but since you're having time issues wouldn't it be good to work with the Lawnchair team together?

**Comment by Fmstrat** [comment] 2024-03-26 16:19
Uhh, is Lawnchair maintained? Releases years ago, commits are package updates, version mismatches on web vs github, etc.

**Comment by John-Gee** [comment] 2024-03-26 17:30
> Uhh, is Lawnchair maintained? Releases years ago, commits are package updates, version mismatches on web vs github, etc.

It is but they also seem to be having some delays getting a release out, so I thought it could be good for both to have help.

**Comment by eleius** [comment] 2024-05-04 16:21
First alpha! [1.0.0-alpha01](https://github.com/NeoApplications/Neo-Launcher/commit/267bc41ccbe4cbdbec2665c36ce43b396a804134)

**Comment by Hund** [comment] 2024-05-04 23:25
> Telegram https://t.me/neo_launcher

Are there people out there that are still using Telegram? It seems weird if it's only shared on some proprietary instant messaging service that nobody uses?

**Comment by Fmstrat** [comment] 2024-05-04 23:58
> > Telegram https://t.me/neo_launcher
> 
> Are there people out there that are still using Telegram? It seems weird if it's only shared on some proprietary instant messaging service that nobody uses?

Yea. Super weird not to use the GitHub releases. Won't be installing Telegram, that's for sure.

**Comment by machiav3lli** [comment] 2024-05-05 08:12
Am not really sure how to respond on a proprietary platform like Github on such comments, but we also provide the test builds over at our [matrix community](https://matrix.to/#/#neo-launcher:matrix.org). Furthermore if you'd like to avoid all proprietary platforms, here's our projects on [Gitlab](https://gitlab.com/NeoApplications) and [Codeberg](https://codeberg.org/NeoApplications)

**Comment by machiav3lli** [comment] 2024-05-05 08:22
And one last thing, if you haven't read that elsewhere: we provide the test only in the community channels/groups to avoid spamming reports on GH/GL/CB as communication is far more complicated here. Just check how many (duplicate) issues on GH have only the intial not-much-informing report of a user with no follow ups…

The community there also helps taking care of duplicate reports directly (so reporters don't have to wait days, sometime) and helping new users to get along.

**Comment by Hund** [comment] 2024-05-05 09:16
Thanks for the clarification. We'll just have to wait for the first stable release then. :)

**Off-topic:**

(Feel free to delete/hide this post)

@machiav3lli:

> Am not really sure how to respond on a proprietary platform like Github on such comments, but we also provide the test builds over at our [matrix community](https://matrix.to/#/#neo-launcher:matrix.org). Furthermore if you'd like to avoid all proprietary platforms, here's our projects on [Gitlab](https://gitlab.com/NeoApplications) and [Codeberg](https://codeberg.org/NeoApplications)

Thanks! I didn't know you had a repository on Codeberg. That's good!

@Turhvjbufv:

> Telegram is open source tho the servers are not, and GitHub isn't open source at all so???

There's a lot of good alternatives to Telegram, that's open source, decentralized and federated, as well as platform agnostic. I see no reason to use Telegram, but I do understand that some people just don't care about those things. I wasn't aware that Telegram was still a thing though. I haven't seen anyone using it in a long time. :)

And yes. I understand that some might think it's ironic that I question a proprietary instant messaging service, on a proprietary code hosting web service.

I'm not some 'FOSS-y purist', but I try to only use open source software when it's possible, and when it's not, I do my best to avoid whatever it may be.

With GitHub, I've made the pragmatic decision to have an account here, even though I don't like it, but it means that I can make actual contributions to projects and get help from projects that stubbornly refuse to use anything else.

Also. As a user, I don't have to run any proprietary software on my computer, other than some JavaScript in the web browser. Ans it's not me who have invested time and effort into this proprietary service. It's not me who have locked myself in here. It's not my headache when Microsoft does something stupid and screw everyone over. :)

**Comment by Hund** [comment] 2024-05-05 09:28
@Turhvjbufv 

> Man I feel bad now, didn't mean to attack you just wanted to state some stuff, and yes I totally agree with you

Please, don't feel bad! I didn't felt attacked. :)

**Comment by Fmstrat** [comment] 2024-05-05 13:46
> Am not really sure how to respond on a proprietary platform like Github on such comments, but we also provide the test builds over at our [matrix community](https://matrix.to/#/#neo-launcher:matrix.org). Furthermore if you'd like to avoid all proprietary platforms, here's our projects on [Gitlab](https://gitlab.com/NeoApplications) and [Codeberg](https://codeberg.org/NeoApplications)

Good to hear Matrix is in the mix, and Codeberg. I'll likely switch Obtainium to point there. Thanks for the heads up.
