### ISSUE TITLE
Home screen randomly half reset

### ISSUE THREAD

**Issue by hynow** [NeoApplications/Neo-Launcher#359] opened 2023-06-16 13:45 UTC
## Description

After several months of things working fine, today when I started my phone, my home screen widgets were gone, and my folders were replaced by single apps.  So it is not a complete home screen reset.  Some things are still arranged as expected, but not all.  The icons are still set up fine, and the app drawer is still the same.

## Expected Behavior

The folders and widgets should still be there.

## Actual Behavior

The folders and widgets are gone.  I have not updated the phone or anything to cause this issue.

## Steps to Reproduce

1.Turn on phone
2. Look at phone
3. Feel confused

## Device and OS

* Device:
* Android version: 12
* Launcher version: 0.9.3 
* Rom: Lineage 19

## Logcat

```
your log here
```

**Comment by machiav3lli** [comment] 2023-06-27 00:23
Do you a crash logger (e.g. Scoop) that may caught a crash of NL? Or did you happen to have installed another launcher and tested it for a while?

**Comment by hynow** [comment] 2023-07-01 10:56
No to both, so unfortunately it’s a bit of a mystery. I actually hadn’t used the phone in a couple weeks and when it booted up, it was like this. So I can’t pinpoint an action they caused it besides booting up. 

I had used the phone for months without issue, and hadn’t installed any new apps recently. I will be changing major android versions so it may not matter. 

But I don’t believe the launcher itself had an update, so it’s a bit confusing why things reset out of nowhere.

**Comment by cultab** [comment] 2023-07-01 12:33
Same thing happened here, unfortunately no logs either 😐

**Comment by MochaFrappMc** [comment] 2023-07-09 20:27
I can also say that this has happened to me

**Comment by saulhdev** [comment] 2023-08-01 03:54
duplicate of #337

**Closed by saulhdev** 2023-08-01 03:54 UTC
