### ISSUE TITLE
Data loss again and again

### ISSUE THREAD

**Issue by misterhsp** [NeoApplications/Neo-Launcher#505] opened 2024-12-11 09:45 UTC
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/NeoApplications/Neo-Launcher/issues) and [closed](https://github.com/NeoApplications/Neo-Launcher/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I'm on the latest version.
- [X] I'm not using a test build (alpha/beta/release-candidate).
- [X] This issue contains only one bug.

### Describe the bug

I keep losing my data and the launcher starts like the first time. No more icons on the desktop and the widgets are gone too. Everything has to be redone.

### Expected Behavior

none

### Neo Launcher's Version

0.9.8

### Installation Source

Github/Codeberg/Gitlab releases

### Last Known Working Version

unknown

### Relevant information

Galaxy Note 9 Lineage 20

**Comment by machiav3lli** [comment] 2024-12-11 10:58
Possibly duplicate of #284

**Closed by machiav3lli** 2024-12-11 10:58 UTC
