### ISSUE TITLE
Updating an app causes the app icon to reset to the system's default one

### ISSUE THREAD

**Issue by MatsG23** [NeoApplications/Neo-Launcher#243] opened 2022-09-02 18:30 UTC
## Description
When I update any app, the app logo/icon in the launcher changes to the [default Android one](https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fencrypted-tbn0.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcQfiKDIkESK9Wq7sC-SikNdfXt78HPOut7Ha1k0E3uTzD_8wLxt%26s&sp=1662142870Tf14fed2d207a54ac09ad37f51eb3fb6c2732c30a38cbaa3a2aa827104ef7d6ac).
This issue does not occur in the standard launcher (here: GrapheneOS launcher3).

## Expected Behavior
The app icon should update to the one packagacked in the new version (in most cases just stay the same).

## Actual Behavior
The app icon distinguishes and gets replaced by the [app logo that shows when an app has no icon set](https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fencrypted-tbn0.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcQfiKDIkESK9Wq7sC-SikNdfXt78HPOut7Ha1k0E3uTzD_8wLxt%26s&sp=1662142870Tf14fed2d207a54ac09ad37f51eb3fb6c2732c30a38cbaa3a2aa827104ef7d6ac).

## Steps to Reproduce
1. Download & install Neo-Launcher 0.9.2

2. Set Neo-Launcher as the default start app

3. Update an installed app
     3a) Download & install an old version of e.g. [Molly](https://github.com/mollyim/mollyim-android/releases/download/v5.44.3-1/Molly-v5.44.3-1-FOSS.apk)
     3b) Update the installed app to a newer version (in case of Molly for example [version 5.44.5-1](https://github.com/mollyim/mollyim-android/releases/download/v5.44.5-1/Molly-v5.44.5-1-FOSS.apk
))

## Device and OS
* Device: Google Pixel 6a
* Android version: 13
* Launcher version: 0.9.2
* Rom: GrapheneOS 20220830

**Comment by saulhdev** [comment] 2022-09-03 16:32
Same as #242, #220, #218 
Fixed in commit b116133

**Comment by erazemk** [comment] 2022-09-04 12:05
Any news on when 0.9.3 will be released, so this fix can be included?

**Comment by machiav3lli** [comment] 2022-09-05 05:48
@erazemk  Nope, we're working on migrating settings to Compose and this would take some time. But generally don't ask for ETA.

**Comment by summersab** [comment] 2022-09-06 02:43
> @erazemk  Nope, we're working on migrating settings to Compose and this would take some time. But generally don't ask for ETA.

I don't mean to sound impatient, tell you what to do, or seem demanding, but it _is_ a pretty big bug that may cause you to lose users. About 10% of my app icons have been reset to the system default, and it's starting to make it difficult to find apps by looking for their icons.

Personally, I don't plan on switching launchers. However, this version has has been available for almost a month - other users may not be so patient. I'd recommend pushing a patch before too long instead of waiting on other development to be completed.

**Comment by machiav3lli** [comment] 2022-09-06 08:20
@summersab I think what you're trying to do here is ethically pretty questionable. I wouldn't be bothered by your words personally, but you should reconsider your approach when communicating in FOSS context.

**Comment by saulhdev** [comment] 2022-09-06 13:17
The issue is happening with the default icon shape only, so you can change to any other and that will fix the issue.

**Comment by summersab** [comment] 2022-09-06 14:40
...I'm so confused. There is a (visually) breaking change. Your team has already pushed a patch. I encouraged you to release an out-of-band update to correct the issue instead of waiting to complete your development cycle. What is unethical about this?

**Comment by cryptikon** [comment] 2022-09-21 16:43
I hate to seem pushy, but I have to agree with @summersab. This is a pretty severe bug. 

I am willing to live with it, but I intended to use this launcher to replace Nova launcher on my family's devices and now I can't do that, because this issue would be unacceptable to people that aren't as understanding.

**Comment by summersab** [comment] 2022-09-21 17:22
> As a workaround, you can change the icon shape back and forth to reload the icons.

This does indeed work, but as @cryptikon mentioned, it's a bit of a show-stopper for those who are less technical. I use this launcher on my parents' and grandparents' devices, and there's no way they would remember how to get into the settings to fix the icons. (In fact, one reason I use Neo is because you can lock the desktop, and I DON'T want them to get into the settings to change things).

**Comment by surfrock66** [comment] 2022-10-02 22:27
I have a bunch of old phones used as smart home and media casting remotes around my house and my extended family's houses.  Some kids can't read yet and rely on icons.  This issue is the reason I haven't replaced Nova with Neo across the fleet.

**Comment by seniorm0ment** [comment] 2022-10-10 13:27
Noticed this as well, honestly very annoying.
Pixel 6 Pro, GrapheneOS, Android 13, Neo Launcher F-Droid v0.9.2

**Comment by johnexu** [comment] 2022-10-20 13:42
Waiting for out-of-band update to correct the issue

**Comment by summersab** [comment] 2022-10-20 14:12
> Waiting for out-of-band update to correct the issue

Yeah, they've made it clear that this isn't going to happen, and asking about it is "unethical," somehow (I'm still trying to figure that one out).

I guess we just have to wait until the next release and keep switching icon styles to fix the issue. It's a bit ridiculous that it's been over two months, though... but I don't want to be "unethical" by mentioning that.

**Comment by johnexu** [comment] 2022-10-20 14:44
@summersab It's so sad that the most beautiful and functional launcher I've ever found treats the user's needs like this.
even more with such a trivial bug.
but at last we will wait

**Comment by surfrock66** [comment] 2022-10-20 15:15
Yea, I think it's counterproductive to make demands of people making this software in their free time for free.  I am frustrated by the decision to delay, but I respect the devs decision and understand that publishing an update may take time away from their paid job, their families, etc, and that's not ok either.

**Comment by l3u** [comment] 2022-10-20 16:17
I was just about file a bug report about this and found this one. Nice to see it has been already fixed!

**Comment by summersab** [comment] 2022-10-21 17:06
I completely agree that no one should attack the developers, and I absolutely appreciate the fact that they have developed this launcher in their free time for free. However, I also don't think that developers should attack the users for explaining why a bug is a bigger issue than they may realize. We're trying to help make the product better and grow the user base, after all.

**Comment by saulhdev** [comment] 2022-10-25 22:34
The issue has been fixed. we not released a new build yet since we are moving to material3. Hopefully a stable version will come shortly as soon as the migration is complete.

**Comment by machiav3lli** [comment] 2022-10-28 09:59
It's finally here…

https://github.com/NeoApplications/Neo-Launcher/releases/tag/0.9.3

**Closed by machiav3lli** 2022-10-28 09:59 UTC
Labels: bug

**Comment by johnexu** [comment] 2022-11-07 06:31
Everything was solved and the change to material3 became splendid

**Comment by cryptikon** [comment] 2022-11-10 17:41
I can confirm the bug is fixed. Thanks to everybody involved!

I would like to re-assert that it was never my intention to put pressure on the devs. I know I have no right to demand any kind of change in a free product. I just felt it necessary to convince people that this bug deserved a high priority, because it had an unavoidable impact on virtually every user. I was more concerned about the reputation damage than personal inconvenience.

Thanks again for the excellent work.

**Comment by summersab** [comment] 2022-11-12 05:13
I wholeheartedly agree with you, @cryptikon - ESPECIALLY that last sentence.

**Comment by 2br-2b** [comment] 2022-11-12 06:30
I agree, and I wasn't trying to make it a personal attack. The fact that y'all use GitHub alone shows that y'all are probably at least somewhat familiar with developing software and with how stuff like this works. Again, I agreed and was hoping for a hotfix also.

I've just seen plenty of issue threads turn into many entitled users claiming that an unpaid developer owes them something, which ends up forcing the maintainers to lock the thread and/or become discouraged by the amount of negativity. While I may have been a bit strong in my language, my goal wasn't to attack any of y'all - it was me trying to make sure this discussion remained civil (which, ironically, I'm realizing I may have done in a not-so-civil way). Note that I'm not a contributor or associated with the project - I'm just another user.

Nothing I said here was meant as a personal attack. If anything seemed personal, I'm sorry and that was not the goal. I wish y'all the best and hope all of y'all's future projects go smoothly!
