### ISSUE TITLE
[Crash] Crash when clicking `Backups`: `java.lang.IllegalArgumentException: Illegal pattern character 'n'`

### ISSUE THREAD

**Issue by chr56** [NeoApplications/Neo-Launcher#223] opened 2022-08-10 17:11 UTC
## Description

Crashed when clicking `Backups` in advanced settings.
Caused by `SimpleDateFormat`'s format pattern compilation (?).

## Crash Report
```
Generated by [AppErrorsTracking](https://github.com/KitsunePie/AppErrorsTracking)
===============
[Device Brand]: Redmi
[Device Model]: Redmi K30 5G
[Display]: RQ3A.211001.001
[Android Version]: 11
[API Version]: 30
[Package Name]: com.saggitt.omega
[Error Type]: Jvm
[Crash Time]: 2022.8.11 00:50:26 UTC+8
[Stack Trace]:
java.lang.ExceptionInInitializerError
	at com.saggitt.omega.backup.BackupListFragment.loadLocalBackups(BackupListFragment.kt:156)
	at com.saggitt.omega.backup.BackupListFragment.onRecyclerViewCreated(BackupListFragment.kt:100)
	at com.saggitt.omega.backup.BackupListFragment.onViewCreated(BackupListFragment.kt:77)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalArgumentException: Illegal pattern character 'n'
	at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:934)
	at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:720)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:691)
	at com.saggitt.omega.backup.BackupFile.<clinit>(BackupFile.kt:291)
	... 17 more
```

## Steps to Reproduce

1. Go to `Home Settings`
2. Entering ` Advanced Settings `, clicking `Backups`
3. Crash 

## Device and OS

[Device Model]: Redmi K30 5G
[Android Version]: 11
[Launcher version]: 0.9.1(925)
[ROM]: crDroid 7.13

**Comment by machiav3lli** [comment] 2022-08-10 20:55
Duplicate of #214, next time please read latest issues (open & closed) before opening a new one!

**Closed by machiav3lli** 2022-08-10 20:55 UTC
