### ISSUE TITLE
Launcher Crashes when adding Google Calendar widget

### ISSUE THREAD

**Issue by jimmyjohnjr1203** [NeoApplications/Neo-Launcher#252] opened 2022-09-13 17:06 UTC
## Description

I recently installed the Google Calendar app, and when I try to add one of the widgets to the home screen, Neo Launcher crashes and I am returned to the most recent app I was using.

## Expected Behavior

The Google calendar Widget is added to the home screen

## Actual Behavior

Neo launcher crashes

## Steps to Reproduce

1. Download Google Calendar App
2. Go to the home screen
3. long press and choose widgets
4. Scroll to google calendar and choose either widget
5. Drag one up to add it to the home screen

## Device and OS

* Device: Samsung Galaxy S9
* Android version: 10
* Launcher version: 0.9.2
* Rom: OneUI 2.1

**Comment by saulhdev** [comment] 2022-09-13 19:10
Duplicate of #185

**Closed by saulhdev** 2022-09-13 19:10 UTC
