### ISSUE TITLE
icons reset to default after app update

### ISSUE THREAD

**Issue by lvmm** [NeoApplications/Neo-Launcher#249] opened 2022-09-05 08:37 UTC
## Description
After some apps have been updated via the play store their icons were changed to the default droid icon both on the desktop and in the app drawer. Resetting the phone didn't help, changing icon size in launcher setting did.

## Expected Behavior
Icons shouldn't have changed

## Actual Behavior
icons were changed to the default droid icon

## Steps to Reproduce

1. update some previously installed apps
2. check their icons on the desktop and in the app drawer
3.
4.

## Device and OS

* Device: Sony Xperia 10 IV XQ-CC72
* Android version: 12
* Launcher version: 0.9.2 (izzy)
* Rom: 65.0.A.01134

**Comment by machiav3lli** [comment] 2022-09-05 09:50
Duplicate of #243, #242, #220, #218 …

**Closed by machiav3lli** 2022-09-05 09:50 UTC
