### ISSUE TITLE
Folder styles

### ISSUE THREAD

**Issue by A-7666** [NeoApplications/Neo-Launcher#408] opened 2023-10-08 15:53 UTC
## Description
Add folder styles, like in Nova launcher.

## Expected Behavior
Being able to choose folder style

## Actual Behavior
No such option present

## Steps to Reproduce

-

## Device and OS

* Android version: GrapheneOS, AOSP 13
* Launcher version: v0.9.3

**Comment by saulhdev** [comment] 2023-10-22 21:52
Duplicate of #354

**Closed by saulhdev** 2023-10-22 21:52 UTC
