### ISSUE TITLE
Launcher won't start

### ISSUE THREAD

**Issue by craigh246** [NeoApplications/Neo-Launcher#201] opened 2022-07-27 09:34 UTC
Phone freezes when trying to set as default launcher and brings up message 'neo launcher keeps stopping' when opening after installation. Samsung galaxy A71.

**Comment by machiav3lli** [comment] 2022-07-27 12:23
Possibly a duplicate of #177. Either check the test build in our TG group or wait for the upcoming release.

**Comment by saulhdev** [comment] 2022-08-10 14:40
Fixed on v0.9.1

**Closed by saulhdev** 2022-08-10 14:40 UTC
