### ISSUE TITLE
Launcher randomly erases all home screen layouts (thank goodness for backups but still)

### ISSUE THREAD

**Issue by spart0n654** [NeoApplications/Neo-Launcher#378] opened 2023-07-29 18:47 UTC
Idk what logs or anything to add to this but I'm on Android 14 beta with the pixel fold (not rooted) and neo Launcher is amazing but having this phone for nearly 2 weeks and using neo Launcher from the start it has completely erased my home screens 7 times now with no error or anything, just unlock the phone and empty screen but dock has some icons (not how I left it though). Thankfully I had made back ups but that doesn't fix my widgets only icons. This is by far not a deal breaker, I Just wanted to make sure someone knew about this. If you need any files/logs let me know what to get and/or how to get them.

**Comment by saulhdev** [comment] 2023-08-05 01:38
duplicate of #337

**Closed by saulhdev** 2023-08-05 01:38 UTC
