### ISSUE TITLE
Some problems I'm getting

### ISSUE THREAD

**Issue by Dzrknsd** [NeoApplications/Neo-Launcher#451] opened 2024-02-10 21:56 UTC
I found this app amazing for me its the best launcher app, the only little bug :

When I search in the app drawer, quit and come black, the delete text cross is still there.

Anyway is this app going to get update anyway?

**Comment by machiav3lli** [comment] 2024-02-11 14:35
Yeah we're still working on v1.0.0

**Comment by machiav3lli** [comment] 2024-02-11 14:35
And the issue is already fixed in local builds

**Closed by machiav3lli** 2024-02-11 14:35 UTC
